# Generated by Django 4.1.7 on 2023-02-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bookingdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='doc_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='p_email',
            new_name='patient_email',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='p_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='p_phone',
            new_name='patient_phone',
        ),
    ]
