# Generated by Django 4.1.7 on 2023-02-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_doc_name_bookingdetails_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='doctor_name',
            new_name='doc_name',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='patient_email',
            new_name='p_email',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='patient_name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='patient_phone',
            new_name='p_phone',
        ),
    ]
